//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsenClases
{
    using System;
    using System.Collections.Generic;
    
    public partial class ASIGNATURAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ASIGNATURAS()
        {
            this.MATRICULA = new HashSet<MATRICULA>();
            this.CLASES1 = new HashSet<CLASES>();
        }
    
        public int ID { get; set; }
        public string TITULO { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> ID_PROFESOR { get; set; }
    
        public virtual PROFESORES PROFESORES { get; set; }
        public virtual CLASES CLASES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATRICULA> MATRICULA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CLASES> CLASES1 { get; set; }
        public virtual PROFESORES PROFESORES1 { get; set; }
    }
}
