//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsenClases
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLASES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CLASES()
        {
            this.REGISTROS = new HashSet<REGISTROS>();
        }
    
        public int ID { get; set; }
        public System.DateTime FECHA { get; set; }
        public Nullable<System.TimeSpan> HORA { get; set; }
        public int ID_ASIGNATURA { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<REGISTROS> REGISTROS { get; set; }
        public virtual ASIGNATURAS ASIGNATURAS { get; set; }
        public virtual ASIGNATURAS ASIGNATURAS1 { get; set; }
    }
}
