//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsenClases
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class isenEntities : DbContext
    {
        public isenEntities()
            : base("name=isenEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ALUMNOS> ALUMNOS { get; set; }
        public virtual DbSet<CLASES> CLASES { get; set; }
        public virtual DbSet<PROFESORES> PROFESORES { get; set; }
        public virtual DbSet<REGISTROS> REGISTROS { get; set; }
        public virtual DbSet<ASIGNATURAS> ASIGNATURAS { get; set; }
        public virtual DbSet<MATRICULA> MATRICULA { get; set; }
    }
}
