//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsenClases
{
    using System;
    using System.Collections.Generic;
    
    public partial class REGISTROS
    {
        public int ID_ALUMNO { get; set; }
        public int ID_CLASE { get; set; }
        public Nullable<bool> ASISTE { get; set; }
        public System.DateTime FECHA_REGISTRO { get; set; }
    
        public virtual ALUMNOS ALUMNOS { get; set; }
        public virtual CLASES CLASES { get; set; }
    }
}
